language: node_js
node_js:
- '6'
env:
  matrix:
    secure: Hwut0vPcT8d59yXPUHC2WtxvlOC+urctEFLkoSl3RlLI69WHykXnoUNPObE2CKzxZZjaavAZdzcJidGKloPErkFRpNSsc7vE5yuBHxtkXr5ENw2X8ziFx0H3nu7FMoOT0BX7m9lCj1P0BnCFIiC54g0oWWMcMm24C0rCJUGYxMmuZZOjnNlFFGMutG3JUagude3Ig+2R9WrqTqfXHby1Kp6863PX7DKDs4c0PiHxF6ERKVt/pyU5Y/kH5Fj8noCD8zHqusPyd/5r9u9VmYgk2xwPZU/qYR8/VLh4zmB48GuotFDlXB2DnLvj23x5I6cYq3jywQzrmJYAtP2tSjdLVs47Yx4ZuR3EsvBN4uVVepdJ3VHW+QKHkluxq9tUhewPFqhky6jjTWXvVH4uZB4Fgi3gfEimOjgLEIeOH7MxwEBIGpqvaL5+fXm2hNZ0RSIMvC9FeCfZ61nfqKVrUc7OgjH48tuILhJOjy+FqD6Qduiix+coLE89vKWhfm3k+urDXPcKrnxnqFsPGGh2X0+6qRLRCo+a4OryWv6H8rJpHzEuOKJCjHd9wsvfPwHA0Q8zSacUAjx0qVTw1WHuI0tUHqgZkI6Pqb2iTl5VlCp4AkgTqPQKga66K1/NQkKDvgrIcA6wXxVPGvOy6hezP5T+iREHMPc8L0EdsSw+mr9c1n0=
after_success:
- bash <(curl -s https://codecov.io/bash)