language: node_js
node_js:
- '6'
env:
  matrix:
    secure: lKhIVffcwnbA3wRiwcsWz9BgiAQ7sXeWBheUcAdg8oKiQF/E6FVG0kecSbFE0SQjtKGqwC+lxLQYgmKd1ofQPybMi0QUCUQwoqJm820LPUvkDWK2CEhAjHbfVRpUNQ2rbdJWibDprm0Dq6/Y4hU0fXnQLxpmW/afU3JrBlVwlr9AV80eFjd+o8NleMmJHe2e4eX+aQfHn4e1mumFBDSNe/LZhZ4YTHh5WI1ioz30sq79nY19aFoO6ESoSBG4IahAc1ijc/C2Q3Agey/hJLXaB0xHtgWF/g6vpLZsnAin49jPWk8ZxfJB6Mvs3KzwhQ1A+MEAqWUYTw9bHG/8vPLoBaHCLV9D+NlyJv5xt3suSGK2vGswSKKKje6umL355TutjT5oFwzXQUMwl6boyXArkMnKD8sJP9gBB7JCGla2mus0FJlcUQBMOupLl/YAd7wTtRl7n/9LQhVinIWywl8X75SIwire4/8oXYNSpv7iT6tTaI9pTZu8mjDckfLwMrXR9G4ZJkSC4nvT6Zfe3tysrQ5SjDDSKz6YLvkMguptdIhFWcfCZ81ieqWjuXMcDwt6ULdG9ZDLpJxyG8Z7rZky0Wlft5fdHSa5sydE/YOG5gsQZxrMkuMTATG8cuIa8kY4CqLQ21ky4jOfjs7ain/LEpJTcnyPEgtRsauHVJydJQw=
